# Site settings
author: Matt Lazewski 
title: Matt Lazewski's Blog
header-img: img/home-bg.png
email: matthew.lazewski@gmail.com
copyright_name: Matt Lazewski 
description: > # this means to ignore newlines until "baseurl:"
  An inside look on my bootcamp journey.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  matthewlazewski

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
